---
log_level: DEBUG
cluster:
  namespace: federation-a
  managed: true
network:
  publicHost: federation-a.mip-tds.chuv.cscs.ch
platform-ui:
  ingress:
    className: nginx
    certManagerClusterIssuer: letsencrypt
